### ISSUE TITLE
Add rule to check the usage of `<meta>` viewport 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#82]
- [x] Check for if the <meta> tag is included, and has `width=device-width`.
   
    Note: For iOS 9+ `initial-scale=1` is no longer needed ([1](https://twitter.com/ppk/status/829329567219343360), [2](https://twitter.com/firt/status/829335091142918145))

- [x] Check for values that create bad user experience such as `user-scalable=no`.
- [x] Check for values that are ignored such as `user-scalable`, `min-scale`, and `max-scale`.

    From https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/:

   >  "Now, we ignore the user-scalable, min-scale and max-scale settings. If you have content that disabled zoom, please test it on iOS 10, and understand that many users will be zooming now."

---

See also:

 * https://www.youtube.com/watch?v=8J6EdpXdzqc&t=23m31s
